apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  labels: 
    app.kubernetes.io/name: postgresql
spec: 
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels: 
      app.kubernetes.io/name: postgresql
  template: 
    metadata:
      name: postgresql
      labels: 
        app.kubernetes.io/name: postgresql
    spec:
      containers:
        - name: postgresql
          image: "postgres:14.4"
          imagePullPolicy: IfNotPresent
          volumeMounts: 
            - name: data
              mountPath: /var/lib/postgresql/data
          ports:
          - name: psql
            protocol: TCP
            containerPort: 5432
          env:
            - name: POSTGRES_HOST_AUTH_METHOD
              value: trust
            - name: POSTGRES_PASSWORD
              value: postgres
      volumes: 
        - name: data
          hostPath:
            path: /mnt/pool/service/postgresql/data/14.4
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
  labels:
    app.kubernetes.io/name: postgresql
spec:
  type: LoadBalancer
  ports:
    - name: psql
      protocol: TCP
      port: 5432
      targetPort: psql
  selector:
    app.kubernetes.io/name: postgresql
